import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="dark">
      <head>
        <script
          src="https://kit.fontawesome.com/8bd2e4a581.js"
          crossOrigin="anonymous"
          async></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
